import { GoogleGenAI, Type } from "@google/genai";

async function translate() {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  const englishTranslations = {
    searchPlaceholder: 'Search...',
    sourceLang: 'Source',
    targetLang: 'Target',
    history: 'History',
    clearHistory: 'Clear',
    login: 'Log In',
    register: 'Sign Up',
    pricing: 'Pricing',
    dictionary: 'Dictionary',
    search: 'Search',
    noResults: 'No results found. Try a different search.',
    resultsFor: 'Results for',
    category: 'Category',
    type: 'Type',
    term: 'Term',
    definition: 'Definition',
    example: 'Example',
    freePlan: 'Free',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    getStarted: 'Get Started',
    loginTitle: 'Sign in to FerhengAI',
    loginSubtitle: 'Unlock the full potential of your language journey.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    searchHistoryPlaceholder: 'Filter history...',
    about: 'About',
    contact: 'Contact',
    profile: 'Profile',
    favorites: 'Favorites',
    monthly: 'Monthly',
    yearly: 'Yearly',
    save: 'Save',
    saved: 'Saved',
    facebookLogin: 'Continue with Facebook',
    appleLogin: 'Continue with Apple',
    billingMonthly: 'Billed Monthly',
    billingYearly: 'Billed Yearly (Save 20%)',
    mostPopular: 'Most Popular',
    contactUs: 'Contact Us',
    message: 'Message',
    send: 'Send',
    sendMessage: 'Send Message',
    name: 'Name',
    aboutTitle: 'About FerhengAI',
    aboutText: 'FerhengAI is a state-of-the-art dictionary application designed to bridge language gaps, specifically focusing on Kurdish dialects. Powered by advanced AI, we provide accurate, context-aware definitions and translations.',
    rightsReserved: 'All rights reserved.',
    planFreeFeat1: 'Standard Search Speed',
    planFreeFeat2: '30 Searches / Day',
    planFreeFeat3: 'Basic Definitions',
    planFreeFeat4: 'Ads Supported',
    planProFeat1: 'Lightning Fast (Gemini Flash)',
    planProFeat2: 'Unlimited Searches',
    planProFeat3: 'Advanced Grammar',
    planProFeat4: 'No Ads',
    planEntFeat1: 'API Access',
    planEntFeat2: 'Custom SSO',
    currentPlan: 'Current Plan',
    upgradePro: 'Upgrade to Pro',
    contactSales: 'Contact Sales',
    viewPlans: 'View Plans',
    upgradeText: 'Get synonym trees and ad-free experience.',
    upgradeTitle: 'Upgrade to Pro',
    noFavorites: 'No favorite words yet.',
    gender_masc: 'Masc',
    gender_fem: 'Fem',
    translateFrom: 'TRANSLATE FROM ...',
    kurdishDialect: 'KURDISH DIALECT',
    swapLanguages: 'Swap Languages',
    features: 'Features',
    featuresTitle: 'Everything you need for Kurdish',
    featuresSubtitle: 'Powerful tools designed to make learning and translation effortless.',
    feat1Title: '3 Kurdish Dialects',
    feat1Desc: 'Comprehensive coverage of Kurmanji, Sorani, and Zazaki.',
    feat2Title: 'AI-Powered',
    feat2Desc: 'Lightning-fast translations with advanced AI precision.',
    feat3Title: '10+ Languages',
    feat3Desc: 'Bridge Kurdish with major world languages seamlessly.',
    feat4Title: 'Verified Data',
    feat4Desc: 'Accurate and linguistically verified content.',
    upgradeToProTitle: 'Unlock the Power of Pro',
    upgradeToProDesc: 'Get access to advanced AI features and unlimited translations.',
    upgradeToProBtn: 'Upgrade to Pro',
    stayUpdated: 'Stay updated with FerhengAI',
    mailPlaceholder: 'Enter your email',
    subscribe: 'Subscribe',
    heroBadge: 'The Kurdish Language Dictionary',
    heroTitle: 'Words that bridge worlds.',
    heroSubtitle: 'Discover the beauty of Kurdish — translate between Kurmanji, Sorani, Zazaki and 10 world languages with AI-powered precision.',
    heroStartBtn: 'Start Translating',
    heroLearnMoreBtn: 'Learn More',
    aboutSectionTitle: 'Preserving Kurdish Heritage',
    aboutSectionSubtitle: 'Our mission is to make Kurdish accessible to the world.',
    aboutText1: 'Kurdish is spoken by over 30 million people across the Middle East and diaspora communities worldwide. Yet digital tools for learning and translating Kurdish remain scarce. FerhengAI bridges this gap with modern AI technology.',
    aboutWhyTitle: 'Why Kurdish Matters',
    aboutWhy1: 'Kurdish is one of the largest languages without a nation-state, spoken by 30+ million people across four countries.',
    aboutWhy2: 'Despite its rich literary and oral tradition, Kurdish remains critically underrepresented in digital technology.',
    aboutWhy3: 'Preserving all three dialects — Kurmanji, Sorani, and Zazaki — is essential for the continuity of Kurdish culture and identity.',
    aboutTechTitle: 'Our Technology',
    aboutTechText: 'FerhengAI uses a two-layer approach: advanced AI language models (Claude & Gemini) provide contextually aware translations, while our verification system ensures grammatical gender accuracy for Kurmanji and Zazaki — two dialects where gender is linguistically essential but often incorrectly assigned by standard AI.',
    aboutTeamTitle: 'Our Team',
    aboutTeamText: 'Built by language enthusiasts and technologists who believe every language deserves world-class digital tools.',
    dialectKurmanjiDesc: 'Turkey, Syria, northern Iraq',
    dialectKurmanjiScript: 'Latin script',
    dialectSoraniDesc: 'Iraqi Kurdistan, western Iran',
    dialectSoraniScript: 'Arabic script',
    dialectZazakiDesc: 'Eastern Turkey (Dersim region)',
    dialectZazakiScript: 'Latin script',
    dialectFamilyTitle: 'The Kurdish Language Family',
    dialectFamilyDesc: 'Kurmanji, Sorani, and Zazaki are all Iranian languages belonging to the Indo-European family.',
    dialectFamilyScript: 'Shared historical roots',
    statSpeakers: '30M+ Speakers',
    statDialects: '3 Dialects Supported',
    statLanguages: '10 Source Languages',
    statAI: '2 AI Models',
    statRules: '500+ Verified Gender Rules',
    statSince: 'Since 2025',
    testimonialsTitle: 'Loved by thousands',
    testimonial1Quote: 'The most accurate Kurdish dictionary I have ever used.',
    testimonial1Role: 'Linguist',
    testimonial2Quote: 'It makes learning Kurmanji so much easier.',
    testimonial2Role: 'Student',
    testimonial3Quote: 'A game-changer for my professional translation work.',
    testimonial3Role: 'Translator',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Is FerhengAI free?',
    faq1A: 'Yes, we have a generous free plan with basic features.',
    faq2Q: 'Which dialects are supported?',
    faq2A: 'We currently support Kurmanji, Sorani, and Zazaki.',
  };

  const targetLanguages = [
    { code: 'fr', name: 'French' },
    { code: 'de', name: 'German' },
    { code: 'es', name: 'Spanish' },
    { code: 'it', name: 'Italian' },
    { code: 'ru', name: 'Russian' },
    { code: 'zh', name: 'Chinese' },
    { code: 'ja', name: 'Japanese' },
    { code: 'ko', name: 'Korean' },
    { code: 'ar', name: 'Arabic' },
    { code: 'fa', name: 'Persian' },
    { code: 'pt', name: 'Portuguese' }
  ];

  for (const lang of targetLanguages) {
    console.log(`Translating to ${lang.name}...`);
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Translate the following JSON values from English to ${lang.name}. Keep the keys exactly the same. Return ONLY the JSON object.\n\n${JSON.stringify(englishTranslations, null, 2)}`,
      config: {
        responseMimeType: "application/json",
      }
    });
    
    console.log(`--- ${lang.code} ---`);
    console.log(response.text);
    console.log(`------------------`);
  }
}

translate();
